services:
  - type: web
    name: email-subscription
    env: docker
    plan: free
    rootDir: email-subscription
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SCOPES
        value: read_customers,write_customers
      - key: SHOPIFY_APP_URL
        sync: false
      - key: DATABASE_URL
        sync: false
